### ISSUE TITLE
Server-side Crash

### ISSUE THREAD

**Issue by Joseph14078** [Joseph14078/BonziWORLD#9]
It seems a server-side, user trigger-able crash has been discovered. The stack trace is as follows:
```
{  
   "trace":[  
      {  
         "column":24,
         "file":"./meat.js",
         "function":"User.talk",
         "line":390,
         "method":"talk",
         "native":false
      },
      {  
         "column":13,
         "file":"events.js",
         "function":"Socket.emit",
         "line":182,
         "method":"emit",
         "native":false
      },
      {  
         "column":12,
         "file":"./node_modules/socket.io/lib/socket.js",
         "function":null,
         "line":503,
         "method":null,
         "native":false
      },
      {  
         "column":11,
         "file":"internal/process/next_tick.js",
         "function":"process.internalTickCallback",
         "line":70,
         "method":"internalTickCallback",
         "native":false
      }
   ],
   "stack":[  
      "TypeError: Cannot read property 'text' of undefined",
      "    at User.talk (./meat.js:390:24)",
      "    at Socket.emit (events.js:182:13)",
      "    at ./node_modules/socket.io/lib/socket.js:503:12",
      "    at process.internalTickCallback (internal/process/next_tick.js:70:11)"
   ],
   "level":"error",
   "message":"uncaughtException: Cannot read property 'text' of undefined"
}
```
This was first reported at #8 and possibly #7. The official server will be taken offline until a bugfix is created.

**Comment by Joseph14078** [comment]
This should be resolved in 665ab270aeefb3f75b2a289989c2ec9d32c1b475. Will re-open the official server in a few moments.
